name: Generate Documentation

on:
  push:
    branches:
      - main  # O la rama en la que estás trabajando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Doxygen
      run: sudo apt-get install doxygen

    - name: Create docs/html folder
      run: |
        mkdir -p docs/html  # Crea la carpeta docs/html si no existe

    - name: Generate documentation with Doxygen
      run: doxygen Doxyfile  # Asegúrate de que el archivo Doxyfile esté en el repositorio

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html  # Asegúrate de que esta ruta sea correcta
